### ISSUE TITLE
Site theme CSS is blocked in the browser

### ISSUE THREAD

**Issue by T-Fletcher** [justafish/ddev-drupal-core-dev#15]
Hi, after installing Drupal and loading the site in the browser, no styles render. This happens with both the Minimal and Standard install profiles. 

Checking the console shows the minified theme CSS is being blocked:

```bash
The resource from “css_1234.css" was blocked due to MIME type ("text/html") mismatch (X-Content-Type-Options: nosniff)
```

However accessing the CSS uri directly is met with a 500 error. 

@simesy suggested running `ddev exec yarn --cwd="core"` from the `post-install-actions` item in the `install.yaml` script.

I'm not sure what this does, but it worked nicely and the theme CSS could load correctly.

---
Tested on:

- MacOS 14.0 Senoma, Intel core i9
- DDEV 1.22.7
- yarn 4.1.1 (after implementing [this fix](https://github.com/justafish/ddev-drupal-core-dev/issues/12))
- Firefox 124.0

**Comment by simesy** [comment]
This happened at DrupalSouth code sprint, and i'm not 100% sure why it only happened for you @T-Fletcher !

> yarn 4.1.1 (after implementing https://github.com/justafish/ddev-drupal-core-dev/issues/12)

I assume after we fixed the yarn issue, we didn't run `ddev get justafish/ddev-drupal-core-dev` again, but I was switching between different people so i'm not sure.

I'll be reviewing the setup steps soon - I hadn't noticed the readme changes in https://github.com/justafish/ddev-drupal-core-dev/commit/cef0e470203098c6df4afe5b1356ad6440ef3f6f until we started setting people up, but it was good improvement thanks @justafish

**Comment by T-Fletcher** [comment]
@simesy That may be the cause, I'll try a totally fresh run through the steps to confirm.

I always find it useful capturing what breaks the process e.g running through it once and reinstalling Drupal resulting in a database error, so there's less and less undocumented errors for people to encounter.

**Comment by rpkoller** [comment]
> @simesy suggested running ddev exec yarn --cwd="core" from the post-install-actions item in the install.yaml script.

it is executing `yarn --cwd="core"` inside in the root of the container which is at `/var/www/html`, and `--cwd="core"` is basically telling yarn to run instead of in `/var/www/html`  in `/var/www/html/core` instead.

**Comment by T-Fletcher** [comment]
I tried several full runthroughs of the install steps and didn't encounter the issue again - I'm guessing it was introduced in my first attempt that involved re-running individual steps. 

I'll close this if no one else can replicate it. Thanks for the help everyone :)
