### ISSUE TITLE
Chrome image

### ISSUE THREAD

**Issue by Berdir** [justafish/ddev-drupal-core-dev#3]
Is there a reason you picked the seleniarm/standalone-chromium image? Performance on OSX?

I'm using the official drupalci packages, so you have the same as on DrupalCI/GitlabCI test runs: drupalci/webdriver-chromedriver:production.

**Comment by justafish** [comment]
@Berdir :wave: the seleniarm image includes noVNC so you can watch the tests running in real-time in the browser https://github.com/justafish/ddev-drupal-core-dev#nightwatch-examples

I also hope to use it to test higher versions of chrome when https://www.drupal.org/project/drupal/issues/3240792 is resolved and then work on supporting firefox
