### ISSUE TITLE
Depend on ddev/ddev-selenium-standalone-chrome instead of directly using seleniarm/standalone-chromium

### ISSUE THREAD

**Issue by rfay** [justafish/ddev-drupal-core-dev#32]
Currently this add-on uses seleniarm/standalone-chromium in its own docker-compose.core-dev-selenium.yaml

But the [ddev/ddev-selenium-standalone-chrome](https://github.com/ddev/ddev-selenium-standalone-chrome) is well-maintained and provides these facilities.

What about requiring that add-on as a dependency instead of requiring the docker-compose.core-dev-selenium.yaml here?

**Comment by justafish** [comment]
Thanks for the suggestion! I'd like to keep control over the image version being used though, and I do intend to complete the firefox support :smiley_cat:
