### ISSUE TITLE
add a fixed version of core's InstallCommand

### ISSUE THREAD

**Issue by joachim-n** [justafish/ddev-drupal-core-dev#36]
Core's InstallCommand makes assumptions about Drupal's location. There's no workaround for this -- they're hardcoded.

One fix would be for this add-on to provide its own fixed version of the InstallCommand class -- there is one in the MR for https://www.drupal.org/node/1792310.

Though there's also an issue to make Drush commands work with this - #29 - in which case fixing `drupal install` might not be necessary.

**Comment by justafish** [comment]
This addon is geared towards developing core with the git checkout so it does make an assumption about Drupal's location. Please feel free to re-open if this changes in core.

**Comment by joachim-n** [comment]
It is, but it would be good if it also supported developing core when installed using a Composer path repository. This is the standard way of developing a Composer package in the wider context of a project.
