### ISSUE TITLE
ddev drupal install says site installed but no tables in database

### ISSUE THREAD

**Issue by kekkis** [justafish/ddev-drupal-core-dev#4]
I'm following the readme instructions and reach the `ddev drupal install` phase.

```
$ ddev drupal install


 Select an installation profile [Install with commonly used features pre-configured.]:
  [standard  ] Install with commonly used features pre-configured.
  [minimal   ] Build a custom site without pre-configured functionality. Suitable for advanced users.
  [demo_umami] Install an example site that shows off some of Drupal’s capabilities.
 >

17/17 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]
Congratulations, you installed Drupal!
Username: admin
Password: <password>
```

then I run `echo 'show tables' |ddev mysql` and nothing is shown, indicating that the DB is in fact empty.

**Comment by justafish** [comment]
@kekkis have you customised anything in your drupal core checkout? When you run `ddev drupal login` does the generated link work?

**Comment by kekkis** [comment]
@justafish, no customisation has happened except that I cloned the repo into a directory called `drupal-core` instead of `drupal`. The link results in a valid-looking URL (https://drupal-core.ddev.site/user/reset/1/1699618202/dVx_Kz-eyw9pLFLiqSiDQzu4xdF1cZ1476q0GncahoM) which fails with HTTP 404 "File not found" obviously being sent by nginx.

**Comment by kekkis** [comment]
Same happens even if I use a directory called `drupal` for the git clone.

**Comment by kekkis** [comment]
I think I have made a mistake at first because following the instruction to the letter actually now did give me a working site installed. Sorry for the false alarm.
