### ISSUE TITLE
New tagged release?

### ISSUE THREAD

**Issue by mxr576** [justafish/ddev-drupal-core-dev#40]
It looks like[ the latest commit ](https://github.com/justafish/ddev-drupal-core-dev/commit/cd06f6cea7781286c769dc4129ed672bb29c316f)is important, but it is only available in `main`.

`ddev get justafish/ddev-drupal-core-dev` installs the latest tagged release and if somebody gets that and follows the latest README.md from the main branch, they could bump into unexpected issues, I guess.

```
❯ ddev get justafish/ddev-drupal-core-dev
Installing justafish/ddev-drupal-core-dev:v0.0.11 
```

**Comment by justafish** [comment]
done :+1:
