### ISSUE TITLE
xDebug breakpoints in tests do not pause execution

### ISSUE THREAD

**Issue by andy-blum** [justafish/ddev-drupal-core-dev#6]
I tried adding an xDebug breakpoint in a phpunit test and then ran `ddev phpunit /path/to/test.php` and it blew right past that spot. Is it possible to debug tests in this way?

**Comment by tyler36** [comment]
I added a breakpoint on `autoload.php`, ran the following command and it stopped:

```shell
ddev exec phpunit -c ./core/phpunit.xml
```

Did you remember to `ddev xdebug on` before the test?

**Comment by andy-blum** [comment]
I would have sworn I'd done everything correctly (xdebug on & vscode listening) but I was just able to make it work. 🤷‍♂️
