### ISSUE TITLE
Addon does not work in installations where drupal is installed as recommended-project

### ISSUE THREAD

**Issue by andy-blum** [justafish/ddev-drupal-core-dev#7]
If Drupal is installed using the recommended project composer template, then the core directory is in `/var/www/html/web/` rather than `/var/www/html/`. This breaks the paths in this addon placing phpunit.xml 

Would it be possible to attempt to detect the existence of the `core` directory before attempting to copy/alter files into that directory?

**Comment by justafish** [comment]
discussed on Slack, summary:
this project isn't intended to support installation in that way, just for direct git clones. If Drupal is installed using the project composer template then something like [Drainpipe](https://github.com/lullabot/drainpipe) is more appropriate
